#!/usr/bin/env ruby

require_relative 'lib/rap'
require_relative 'runner'

def main(input_path, verbose=nil, silent=nil, help=nil, initial_function: "main")
    source = File.read(input_path)
    runner = Runner.new(source, input_path)
    begin
        runner.run(initial_function)
    rescue StandardError => e
        if verbose
            p e
        end
    end
end

RubyArgParse.call(method(:main))